import { useState } from 'react';
import { Alert, Button, Card, Statistic, Typography, Upload, message } from 'antd';
import { FileAddOutlined } from '@ant-design/icons';
import styled from '@emotion/styled';
import { importData, isClient, isOrder, isPayment } from '@shared/lib/import/dataImport';
import { useClientStore } from '@entities/client/model/clientStore';
import { useOrderStore } from '@entities/order/model/orderStore';
import { usePaymentStore } from '@entities/payment/model/paymentStore';
const Header = styled.div({ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginBottom: 24, flexWrap: 'wrap' });
const Summary = styled.div({ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: 16, marginTop: 24, '@media (max-width: 700px)': { gridTemplateColumns: '1fr' } });
export function ImportPage() { const [api, contextHolder] = message.useMessage(); const [result, setResult] = useState<Awaited<ReturnType<typeof importData>> | null>(null); const { replaceClients } = useClientStore(); const { replaceOrders } = useOrderStore(); const { replacePayments } = usePaymentStore(); const handleFile = async (file: File) => { try { const parsed = await importData(file); setResult(parsed); replaceClients(parsed.clients.filter(isClient)); replaceOrders(parsed.orders.filter(isOrder)); replacePayments(parsed.payments.filter(isPayment)); api.success('Импорт завершён'); } catch (error) { api.error(error instanceof Error ? error.message : 'Не удалось импортировать файл.'); } return false; }; return <>{contextHolder}<Header><div><Typography.Title level={2}>Импорт</Typography.Title><Typography.Text type="secondary">Загрузка данных из Excel, CSV или JSON</Typography.Text></div><Upload accept=".xlsx,.xls,.csv,.tsv,.json" showUploadList={false} beforeUpload={handleFile}><Button type="primary" icon={<FileAddOutlined />}>Выбрать файл</Button></Upload></Header><Card title="Поддерживаемые форматы"><Typography.Paragraph>Excel и CSV импортируют клиентов по столбцам «Имя», «Телефон», «Город», «Комментарий». JSON принимает объект с массивами clients, orders и payments.</Typography.Paragraph>{result && <><Alert type="success" showIcon message="Данные сохранены в локальную базу." description={result.warnings.join(' ') || undefined} /><Summary><Statistic title="Клиенты" value={result.clients.length} /><Statistic title="Заказы" value={result.orders.length} /><Statistic title="Платежи" value={result.payments.length} /></Summary></>}</Card></>; }
