import ExcelJS from 'exceljs';
import type { Client, Order, Payment } from '@shared/types/models';

export interface ImportResult { clients: Client[]; orders: Order[]; payments: Payment[]; warnings: string[] }
type Cell = string | number | Date | null | undefined;
const createId = () => `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
const text = (value: Cell) => value instanceof Date ? value.toISOString() : String(value ?? '').trim();
const date = (value: Cell) => { const parsed = value instanceof Date ? value : new Date(text(value)); return Number.isNaN(parsed.getTime()) ? new Date().toISOString() : parsed.toISOString(); };
const parseCsv = (value: string): string[][] => { const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false; for (let index = 0; index < value.length; index += 1) { const char = value[index]; if (char === '"' && value[index + 1] === '"') { cell += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if (!quoted && (char === ',' || char === ';' || char === '\t')) { row.push(cell.trim()); cell = ''; } else if (!quoted && (char === '\n' || char === '\r')) { if (char === '\r' && value[index + 1] === '\n') index += 1; row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); row = []; cell = ''; } else cell += char; } row.push(cell.trim()); if (row.some(Boolean)) rows.push(row); return rows; };
const fromRows = (rows: string[][]): ImportResult => { const [header = [], ...data] = rows; const keys = header.map((item) => item.toLocaleLowerCase('ru-RU')); const value = (row: string[], names: string[]) => row[keys.findIndex((key) => names.some((name) => key.includes(name)))] ?? ''; const clients = data.filter((row) => value(row, ['имя', 'клиент', 'name']).length > 0).map((row) => ({ id: createId(), name: value(row, ['имя', 'клиент', 'name']), phone: value(row, ['телефон', 'phone']), city: value(row, ['город', 'city']), comment: value(row, ['коммент', 'comment']), createdAt: date(value(row, ['создан', 'дата', 'created'])) })); return { clients, orders: [], payments: [], warnings: clients.length ? [] : ['Не найден столбец с именем клиента.'] }; };
const normalizeJson = (data: unknown): ImportResult => { if (!data || typeof data !== 'object') throw new Error('JSON должен содержать объект или массив.'); const source = data as { clients?: unknown; orders?: unknown; payments?: unknown; format?: string; data?: Record<string, string> }; if (source.format === 'facade-good-backup' && source.data) throw new Error('Файл резервной копии восстанавливается в разделе «Резервное копирование».'); const array = (value: unknown) => Array.isArray(value) ? value : []; return { clients: array(source.clients) as Client[], orders: array(source.orders) as Order[], payments: array(source.payments) as Payment[], warnings: [] }; };
export async function importData(file: File): Promise<ImportResult> { const extension = file.name.toLowerCase().split('.').pop(); if (extension === 'json') return normalizeJson(JSON.parse(await file.text()) as unknown); if (extension === 'csv' || extension === 'tsv') return fromRows(parseCsv(await file.text())); if (extension === 'xlsx' || extension === 'xls') { const workbook = new ExcelJS.Workbook(); await workbook.xlsx.load(await file.arrayBuffer()); const sheet = workbook.worksheets[0]; const rows: string[][] = []; sheet.eachRow((row) => rows.push((row.values as Cell[]).slice(1).map(text))); return fromRows(rows); } throw new Error('Поддерживаются только форматы Excel, CSV и JSON.'); }
export const isClient = (value: Client): boolean => Boolean(value.id && value.name);
export const isOrder = (value: Order): boolean => Boolean(value.id && value.clientId && value.number);
export const isPayment = (value: Payment): boolean => Boolean(value.id && value.orderId && value.amount >= 0);
